services:
  postgres:
    image: postgres:16
    container_name: resume_blueprint_postgres
    restart: unless-stopped
    ports:
      - "55434:5432"
    environment:
      POSTGRES_DB: resume_blueprint_db
      POSTGRES_USER: rb_user
      POSTGRES_PASSWORD: rb_password
    volumes:
      - rb_pgdata:/var/lib/postgresql/data

volumes:
  rb_pgdata:
